In [1]:
from sklearn.datasets import load_iris #import the iris dataset

In [2]:
iris=load_iris() #load the iris dataset

In [3]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print(iris['data'])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
print(iris['target'] )

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
print(iris['feature_names']) #features

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [7]:
print(iris['target_names']) #3 classes

['setosa' 'versicolor' 'virginica']


In [8]:
print(iris['DESCR'] )#statistic summary

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [9]:
iris['data'].shape

(150, 4)

# Train-Test Split (Hold out validation)

In [10]:
#import the libraries
from sklearn.model_selection import train_test_split #library for hold out validation 
from sklearn.metrics import r2_score #performance metrics
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold  #library for k-fold validation
from sklearn.model_selection import StratifiedKFold #library for Stratified K-fold cross validation
from sklearn.model_selection import LeaveOneOut #library for leave one out cross validation

In [11]:
x_train,x_test,y_train,y_test=train_test_split(iris['data'],iris['target'],random_state=3)

In [12]:
x_train.shape

(112, 4)

In [13]:
x_test.shape

(38, 4)

### Logistic Regression

In [14]:
model=LogisticRegression()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(r2_score(y_test,y_pred))

0.9609053497942387


C:\Users\RAVI\anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### KNeighborsClassifier

In [15]:
model=KNeighborsClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(r2_score(y_test,y_pred))

0.9218106995884774


### RandomForestClassifier

In [16]:
model=RandomForestClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(r2_score(y_test,y_pred))

0.9218106995884774


## K-fold cross validation

### Logistic Regression

In [17]:
model=LogisticRegression()
kfold=KFold(8)
out=cross_val_score(model,iris['data'],iris['target'],cv=kfold)
print(out) #8 outputs for each fold
print(np.mean(out)) #get the mean of 8 outputs

[1.         1.         1.         0.94736842 0.89473684 0.94736842
 0.88888889 0.88888889]
0.945906432748538


C:\Users\RAVI\anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\RAVI\anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html

### KNeighborsClassifier

In [18]:
model=KNeighborsClassifier()
kfold=KFold(8)
out=cross_val_score(model,iris['data'],iris['target'],cv=kfold)
print(out) #8 outputs for each fold
print(np.mean(out)) #get the mean of 8 outputs

[1.         1.         1.         0.84210526 0.89473684 0.94736842
 0.94444444 1.        ]
0.9535818713450293


### RandomForestClassifier

In [19]:
model=RandomForestClassifier()
kfold=KFold(8)
out=cross_val_score(model,iris['data'],iris['target'],cv=kfold)
print(out) #8 outputs for each fold
print(np.mean(out)) #get the mean of 8 outputs

[1.         1.         1.         0.94736842 0.89473684 0.94736842
 0.94444444 0.83333333]
0.945906432748538


## Stratified k-fold cross validation

### LogisticRegression

In [20]:
skfold=StratifiedKFold(n_splits=5)
model=LogisticRegression()
out=cross_val_score(model,iris['data'],iris['target'],cv=skfold)
print(out) #5 outputs for each fold
print(np.mean(out)) #get the mean of 5 outputs

[0.96666667 1.         0.93333333 0.96666667 1.        ]
0.9733333333333334


C:\Users\RAVI\anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### KNeighborsClassifier

In [21]:
skfold=StratifiedKFold(n_splits=5)
model=KNeighborsClassifier()
out=cross_val_score(model,iris['data'],iris['target'],cv=skfold)
print(out) #5 outputs for each fold
print(np.mean(out)) #get the mean of 5 outputs

[0.96666667 1.         0.93333333 0.96666667 1.        ]
0.9733333333333334


### RandomForestClassifier

In [22]:
skfold=StratifiedKFold(n_splits=5)
model=RandomForestClassifier()
out=cross_val_score(model,iris['data'],iris['target'],cv=skfold)
print(out) #5 outputs for each fold
print(np.mean(out)) #get the mean of 5 outputs

[0.96666667 0.96666667 0.93333333 0.93333333 1.        ]
0.96


## Leave one out cross validation

### RandomForestClassifier

In [23]:
model=RandomForestClassifier()
loo=LeaveOneOut()
out=cross_val_score(model,iris['data'],iris['target'],cv=loo)
print(np.mean(out)) 

0.9533333333333334


### KNeighborsClassifier

In [24]:
model=KNeighborsClassifier()
loo=LeaveOneOut()
out=cross_val_score(model,iris['data'],iris['target'],cv=loo)
print(np.mean(out)) 

0.9666666666666667
